development
antonh96/ETSN20_lab4 pull request #1
Opened 2020-12-02 09:42 UTC by antonh96

2020-12-02 09:43 UTC, antonh96 reviewed
Test

2020-12-04 09:41 UTC, mariahellstrand requested changes

2020-12-04 09:41 UTC, mariahellstrand commented on lab4/src/Search.java
> +    private void searchPattern(String pattern, String filepath) throws FileNotFoundException {
Maybe add some comment about the method "searchPattern"

2020-12-04 09:41 UTC, mariahellstrand commented on lab4/src/Search.java
> +    public static void main(String[] args) throws FileNotFoundException {
you can consider using a try-catch block instead of throws since in this solution you never actually handle the exception to be thrown

2020-12-04 09:41 UTC, mariahellstrand commented on lab4/src/Search.java
> +    private void searchPattern(String pattern, String filepath) throws FileNotFoundException {
"searchPattern" is working in a good way since it is clear and simple to understand

2020-12-04 09:41 UTC, mariahellstrand commented on lab4/src/Search.java
> +    }
consider closing the scanner

2020-12-04 09:41 UTC, mariahellstrand commented on lab4/src/Search.java
> +    private void searchPattern(String pattern, String filepath) throws FileNotFoundException {
good variable names

2020-12-04 09:51 UTC, mariahellstrand approved these changes

2020-12-04 09:53 UTC, merged